name: skybnb
description: App de gestión de propiedades para Skybnb
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.2

  # Formateo de fechas y monedas
  intl: ^0.18.1
  
  # HTTP para requests a la API REST
  http: ^1.1.0
  
  # Calendario
  table_calendar: ^3.0.9
  
  # Imágenes con cache
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png